openapi: 3.0.1
info:
  title: User Service API
  version: '1.0'
paths:
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: List of users
    
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
        '404':
          description: Not found
    patch:
      summary: Update user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Updated user
        '400':
          description: Update failed
components:
  schemas:
    UserUpdate:
      type: object
      properties:
        displayName:
          type: string
        role:
          type: string
